### ISSUE TITLE
Added new commands 

### ISSUE THREAD

**Issue by Akovognon2003** [DFRobot/DFRobot_SU03T#1]
How do I add other voice commands to the SU-03T module and what software should I use to do so?

**Comment by qsjhyy** [comment]
I'm sorry, the module corresponding to this library does not support custom voice commands. Perhaps you can take a look at another module: https://wiki.dfrobot.com.cn/SKU_SEN0539_Gravity_Voice_Recognition_I2C_UART.

**Comment by qsjhyy** [comment]
Due to a lack of further communication for an extended period, this issue has been closed. If there is a need in the future, it can be reopened at any time.
